Add missing include to fix build failure with new compiler in Debian
 /<<PKGBUILDDIR>>/zypp/target/rpm/RpmHeader.cc: In function ‘int unameToUid(const char*, uid_t*)’:
 /<<PKGBUILDDIR>>/zypp/target/rpm/RpmHeader.cc:41:16: error: ‘strcmp’ was not declared in this scope
    41 |     } else if (strcmp(thisUname, "root") == 0) {